---

- hosts: all
  become: true  #sudo
  pre_tasks:  # pre_tasks mandates that these tasks run 1st.  won't affect this because this is from top to bottom.

  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package and update cache for Ubuntu 
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in [ "Debian", "Ubuntu" ]

  - name: install httpd and php package and update cache for Centos
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd service (centos doesn't start it by default) 
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name:  install mariadb package (CentOS)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name:  install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name:  install samba apackage
    package:
      name: samba
      state: latest
